[package]
name = "rusty_bird"
version = "0.1.0"
authors = ["Ivan Kupalov <ivan.kupalov@icloud.com>"]

[dependencies]
hyper = "*"
rustc-serialize = "0.3"
rand = "0.3"
time = "0.1"
rust-crypto = "^0.2"

[dependencies.url]
git = "https://github.com/servo/rust-url"
